version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: student_db
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: alibou
      POSTGRES_PASSWORD: alibou
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: